# Generated by Django 3.1.4 on 2020-12-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Todo', 'verbose_name_plural': 'Todo'},
        ),
        migrations.AlterField(
            model_name='todo',
            name='item',
            field=models.TextField(max_length=250),
        ),
    ]
